# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin post to the top'),
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pinned', '-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-pinned', '-created_at'], name='api_post_pinned_created_idx'),
        ),
    ]

